[package]
name = "noteable"
version = "0.1.0"
description ="still in alpha!"
authors = ["Toby Devlin <toby@tobydevlin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
chrono = { version = "0.4", features = ["serde"] }
yaml-rust = "0.4.3"
csv = "1.1.3"
serde = { version = "1", features = ["derive"] }
ansi_term = "0.12.1"