name: Build & Test

on:
  push:

env:
  MIN_SUPPORTED_RUST_VERSION: "1.62.0"

jobs:
  build:
    strategy:
      matrix:
        build_platform: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
    runs-on: ${{ matrix.build_platform }}
    steps:
      - name: Install rust toolchain (v${{ env.MIN_SUPPORTED_RUST_VERSION }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.MIN_SUPPORTED_RUST_VERSION }}
          default: true
          profile: minimal # minimal component installation (ie, no documentation)
          components: clippy

      - uses: actions/checkout@v2

      - name: Format
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose --release

      - name: Run tests
        run: cargo tests --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build ${{ matrix.build_platform }}
          path: ${{ github.workspace }}/target/release/scribr.*
